spring:
  datasource:
    url: jdbc:h2:file:${H2_DB_PATH:./data/bankingdb}
    driver-class-name: org.h2.Driver
    username: ${H2_DB_USERNAME:sa}
    password: ${H2_DB_PASSWORD:password}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: application

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
