spring:
  datasource:
    url: jdbc:h2:file:${H2_DB_PATH:./data/bankingdb}
    driver-class-name: org.h2.Driver
    username: ${H2_DB_USERNAME:sa}
    password: ${H2_DB_PASSWORD:password}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: application
  security:
    oauth2:
      client:
        registration:
          mock-oauth:
            client-id: mock-client-id
            client-secret: mock-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          mock-oauth:
            authorization-uri: http://localhost:8080/oauth/authorize
            token-uri: http://localhost:8080/oauth/token
            user-info-uri: http://localhost:8080/userinfo
            user-name-attribute: sub

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
